### PR TITLE
Add basic documentation

### PR DESCRIPTION
**Pull request by TheKodeToad**
Adds some basic documentation.
If it works better, you could create a publicly editable wiki, and I could add some of this documentation there. It might be better to have the documentation in the repository, though, as it means that you can see the documentation for older versions, and it means people can contribute with pull requests, rather than everyone being able to edit it.

### CODE REVIEW

**Comment by TheKodeToad** [comment]
Another alternate is linking a public GitHub repository to the wiki, maybe something like [this](https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html) (but adapted to use Actions), meaning that pull requests are required to edit the wiki.

**Comment by thatgoofydev** [comment]
Because of the below reasons, I am not going to merge this. However it is a good start and we will reference it when creating the documentation.

1. A lot of the stuff you documented will be outdated when the new plugin system gets released. (probably next week or the one after)
2. We have not decided how/where we are going to post the documentation. But one things we agree on is that this repository is probably not the best place.

For the time being documentation is not our main focus. We are still refactoring a many areas of the API, so the documentation would just be out of date every 2 weeks. This is why we keep the example plugin up to date, it's an helping hand for getting started.
The goal of the API is to be as developer friendly as possible (self explanatory, easy to use and straight to the point). So, ideally we would not require much documentation. BUT we do realise that it is important (especially for newer developers) to have good documentation. However this is something we will start on once the structure of the API isn't constantly changing.

**Comment by TheKodeToad** [comment]
I agree - I was trying to see if this method worked, but I think ReadTheDocs, GitHub Pages or GitHub wiki would better.

**Comment by TheKodeToad** [comment]
I won't delete the branch, in case you find it useful when creating documentation in the future.

**Pull request closed without merging**
