### PR TITLE
Better Command API

### PR DESCRIPTION
**Pull request by TheKodeToad**
Attempt to improve the Command API (draft).
Removes ChatColor to be replaced with NamedTextColor and MiniMessage (messages parsed in a format similar to HTML), both included in Adventure Text API.
Also adds a `--developer` flag which activates the `SharedConstants.RUNNING_IN_IDE` field.
Currently contains no implementation.

- [x] Argument types
- [x] Flat commands (recreating old system, for cross-platform plugins such as WorldEdit)
- [ ] Add implementation
- [x] Command builder
- [ ] Improve API with inspiration from [Minestom](https://github.com/Minestom/Minestom/tree/master/src/main/java/net/minestom/server/command/)  

Currently the API is not that great, so I think I'll take inspiration from [Minestom](https://github.com/Minestom/Minestom), which already has a [fully working Command API](https://github.com/Minestom/Minestom/tree/master/src/main/java/net/minestom/server/command/).

On hold: this stuff hurts my brain.

### CODE REVIEW

**Comment by TheKodeToad** [comment]
Turns out this is quite hard, so I think I may work on the implementation later.
The code has many used parts.

**Comment by TheKodeToad** [comment]
I'll finish this one day!

**Comment by TheKodeToad** [comment]
That year went fast

**Comment by TheKodeToad** [comment]
Happy 2023 guys!!!!!

**Comment by TheKodeToad** [comment]
Hmm, this doesn't seem to be going anywhere atm

**Comment by MrSlimeDiamond** [comment]
rip better command api

**Comment by TheKodeToad** [comment]
Happy 4th birthday Better Command API
image

**Pull request closed without merging**
