### PR TITLE
option to do everything for you

### PR DESCRIPTION
**Pull request by MrSlimeDiamond**

### CODE REVIEW

**Comment by MrSlimeDiamond** [comment]
I tested it, it works.
I am not sure why I didn't test it before making a pull request.

**Comment by TheKodeToad** [comment]
`setupRepository` already patches the code (I think).

**Comment by MrSlimeDiamond** [comment]
> `setupRepository` already patches the code (I think).

Ah. Well, do it anyway just in case (:

**Comment by MrSlimeDiamond** [comment]
going to close this since its not seeing any activity

**Pull request closed without merging**
